# Exercícios

In [28]:
#pacotes
import pandas as pd

In [29]:
#variaveis default
pd.set_option("display.max_columns", 100)
path = '../dados/atividade1/us_tax_data_2016.csv'
path1 ='../dados/aula3/fcc_survey.xlsx'

1. Crie um dataframe de tax_data_2016.csv que usa apenas as colunas específicas necessárias para ver se há diferenças por geografia e nível de renda na composição familiar.
Para fazer isso, selecione as colunas sobre grupo de renda, são elas: CEP (zipcode), status de declaração de imposto de renda (coluna mars1 para solteiro e MARS2 para casado), e  NUMDEP (número de dependentes).

In [30]:
#colunas solicitadas
dado = pd.read_csv(path, usecols=['zipcode','STATE','mars1','MARS2','NUMDEP'])
dado.head(5)

  STATE  zipcode   mars1   MARS2  NUMDEP
0    AL        0  477700  105350  491310
1    AL        0  211930  142340  360480
2    AL        0   83420  137870  182880
3    AL        0   29420  124060  130160
4    AL        0   20240  188080  195990

2. Obtenha as primeiras 500 linhas em um dataframe chamado primeiras500. 
Em seguida obtenha as próximas 500 linhas em um dataframe proximas500. 
Para fazer isso, use os argumentos ``nrows`` e  ``skiprows`` para obter os registros corretos, 
``header`` para informar aos pandas que os dados não têm nomes de colunas e ``names`` para fornecer os nomes de colunas ausentes.     
Depois, nomeie as colunas em proximos500 fornecendo uma lista de colunas de primeiros500 para o argumento ``names``.
Use a função list() para obter nomes de coluna de primeiros500.

In [43]:
# Lê as primeiras 500 linhas do arquivo 
primeiras500 = pd.read_csv(path, nrows=500, header=None)

primeiras500.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146
0,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,...,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
1,1,AL,0,1,815440,477700,105350,221200,440830,1296920,491310,24730,16610,8130,5440,31550,225140,150920,10610343,815440,10787121,651680,8466376,90040,57551,42420,74527,38170,51048,11830,5328,144430,765184,34770,20594,38510,240402,104980,1038534,8310,22770,65220,37560,73490,7900,17497,145820,176778,1340,308,...,0,0,18830,6579,101150,34290,1760,68,6620,2205,27490,15002,32490,5582,28940,8858,1140,471,113880,155301,54520,230494,56460,231566,18020,10199,755160,2119297,363420,1097024,333760,981026,229900,291625,61350,57108,28510,14474,254700,160665,367320,330066,0,0,0,0,63420,51444,711580,1831661

In [44]:
primeiras500.columns.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146], dtype=int64)

In [46]:
col_names = list(primeiras500)
#tax_data_next500 = pd.read_csv(path, nrows=500, skiprows=1000, header=None, names= col_names)


proximas500 = pd.read_csv(path, skiprows=500, nrows=500, header=None, names=col_names)

print(proximas500)

     0   1      2    3     4     5    6    7     8     9     10   11   12
0      1  AL  35178    2   390   150  120  100   200   760   250    0    0  \
1      1  AL  35178    3   230    60  120   50   140   540   200    0    0
2      1  AL  35178    4   120    30   90    0    80   280    80    0    0
3      1  AL  35178    5   110     0   90    0    80   280    90    0    0
4      1  AL  35178    6    20     0   20    0     0    50     0    0    0
..   ...  ..    ...  ...   ...   ...  ...  ...   ...   ...   ...  ...  ...
495    1  AL  35564    5    40     0   30    0    30   100    30    0    0
496    1  AL  35564    6     0     0    0    0     0     0     0    0    0
497    1  AL  35565    1  2250  1200  520  490  1590  3850  1340   20    0
498    1  AL  35565    2  1270   430  600  220   920  2910  1040    0    0
499    1  AL  35565    3   610   110  470   50   480  1620   540    0    0

     13   14   15   16   17     18    19     20    21     22   23   24   25
0      0    0    0  100   80  13876   390  13943   340  11628   60   41   40  \
1      0    0    0   40   60  13654   230  13737   210  11122   60   23    0
2      0    0    0   30   40   9905   120  10001   100   7247   40   69   20
3      0    0    0    0   60  14233   110  14454   120  12722   80   81   40
4      0    0    0    0    0   7392    20   7392     0      0    0    0    0
..   ...  ...  ...  ...  ...    ...   ...    ...   ...    ...  ...  ...  ...
495    0    0    0    0    0   4328    40   4328    30   2860   20   18    0
496    0    0    0    0    0      0     0      0     0      0    0    0    0
497   20    0  150  500  440  29283  2250  29791  1800  23001  330  186   80
498    0    0   70  230  270  45116  1270  45569  1150  37722  290  240   70
499    0    0    0   60  160  37196   610  37644   560  30799  220  235   60

     26   27   28   29   30   31    32   33   34   35    36   37    38   39
0     82   40   65   50   22   30   103   20  -10   40   338   70  1141    0  \
1      0    0    0   60   36   50   207   30  126   40   513   50  1253   30
2    238   20  141   40   24    0     0    0    0    0     0   40  1274    0
3    158   30  140   60   84   30   373   40  992   30  1163   50  1471    0
4      0    0    0    0    0    0     0    0    0    0     0    0     0    0
..   ...  ...  ...  ...  ...  ...   ...  ...  ...  ...   ...  ...   ...  ...
495    0    0    0    0    0    0     0    0    0    0     0    0     0    0
496    0    0    0    0    0    0     0    0    0    0     0    0     0    0
497  154   70  108   30   14  410  3526   80   21  110   753  210  1691   50
498  197   60  170   90   47  210  2120   60  182  100   756  200  2625   40
499  202   50  171  100   70  100   816   50  213   60   649  120  2304   30

     40   41   42    43   44   45   46   47   48   49   ...  97   98   99
0     40  122   70   479    0    0   60   67    0    0  ...    0    0    0  \
1      0    0   50   691   30  928   50   83    0    0  ...    0    0    0
2      0    0   30   667    0    0   30   96    0    0  ...    0    0    0
3      0    0   40  1083    0    0   50  221    0    0  ...    0    0    0
4      0    0    0     0    0    0    0    0    0    0  ...    0    0    0
..   ...  ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
495    0    0    0     0    0    0    0    0    0    0  ...    0    0    0
496    0    0    0     0    0    0    0    0    0    0  ...    0    0    0
497  130  305   90   152   20   24  420  508    0    0  ...    0    0   80
498  110  272  240  1373   30  244  240  453   30    7  ...    0    0   60
499   60  146  130  1883   50  449  160  448   30    7  ...    0    0   30

     100  101  102  103  104  105  106  107  108  109  110  111  112  113
0      0  160  139    0    0   20   14    0    0   70   14   90   92   30  \
1      0  110  164    0    0   20   17   30   43   30    4   70  128    0
2      0   40   73    0    0    0    0    0    0    0    0   30   60    0
3      0   40   58    0    0    0    0    0    0    0    0   20   33    0
4      0    0    0    0    0    0    0    0    0    0    0    0    0    0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
495    0    0    0    0    0    0    0    0    0    0    0    0    0    0
496    0    0    0    0    0    0    0    0    0    0    0    0    0    0
497   28  250   65    0    0    0    0   30   12  130   20   90   26   20
498   34  580  442    0    0   50   22   50   39  280   58  380  325    0
499   27  340  444   40    2   40   16   60   65  100   17  220  335   30

     114  115  116  117  118  119  120  121  122   123   124   125   126  127
0     10   20   30   20   92   30  107   30   15   380  1595   120   222  100  \
1      0   30   53    0    0    0    0    0    0   220  1452     0     0    0
2      0    0    0    0    0    0    0    0    0   120  1149     0     0    0
3      0   20   60    0    0    0    0    0    0   110  1907     0     0    0
4      0    0    0    0    0    0    0    0    0    20  1215     0     0    0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...  ...
495    0    0    0    0    0    0    0    0    0    30   497     0     0    0
496    0    0    0    0    0    0    0    0    0     0     0     0     0    0
497    4  370  531  210  997  220  987   60   30  2080  5752  1030  2826  900
498    0  160  346   90  403  100  442   90   58  1240  5482   410   951  330
499    7   80  166   20   90   30  122    0    0   600  3967     0     0    0

      128  129  130  131  132  133  134  135   136   137   138  139  140  141
0     189   80   89    0    0    0    0  310   677   320   728    0    0    0  \
1       0    0    0   20   22    0    0  220  1005   220  1052    0    0    0
2       0    0    0    0    0    0    0  110   889   110   931    0    0    0
3       0    0    0    0    0    0    0  110  1757   110  1829    0    0    0
4       0    0    0    0    0    0    0   20  1464    20  1551    0    0    0
..    ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...  ...  ...  ...
495     0    0    0    0    0    0    0   40   501    40   526    0    0    0
496     0    0    0    0    0    0    0    0     0     0     0    0    0    0
497  2476  630  791   50   37  100   69  710   467  1060  1034    0    0    0
498   770  300  427   40   26   30   20  940  1954  1010  2377    0    0    0
499     0   30   44   50   35    0    0  580  2512   590  2721    0    0    0

     142  143  144   145   146
0      0   50   64   330   926
1      0   50  110   170   508
2      0   40   62    80   274
3      0   50  420    70   295
4      0    0    0     0     0
..   ...  ...  ...   ...   ...
495    0    0    0    20    86
496    0    0    0     0     0
497    0  200  182  1940  4871
498    0  160  264  1100  3325
499    0  120  230   480  1434

[500 rows x 147 columns]

In [36]:
# Lê as primeiras 500 linhas do arquivo 
primeiras500 = pd.read_csv(path, nrows=500, header=None)

primeiras500.head(2)

# Lê as próximas 500 linhas, pulando as primeiras 500 já lidas
proximas500 = pd.read_csv(path, skiprows=500, nrows=500, header=None, names=list(primeiras500.columns))

proximas500.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146
0,1,AL,35178,2,390,150,120,100,200,760,250,0,0,0,0,0,100,80,13876,390,13943,340,11628,60,41,40,82,40,65,50,22,30,103,20,-10,40,338,70,1141,0,40,122,70,479,0,0,60,67,0,0,...,0,0,0,0,160,139,0,0,20,14,0,0,70,14,90,92,30,10,20,30,20,92,30,107,30,15,380,1595,120,222,100,189,80,89,0,0,0,0,310,677,320,728,0,0,0,0,50,64,330,926
1,1,AL,35178,3,230,60,120,50,140,540,200,0,0,0,0,0,40,60,13654,230,13737,210,11122,60,23,0,0,0,0,60,36,50,207,30,126,40,513,50,1253,30,0,0,50,691,30,928,50,83,0,0,...,0,0,0,0,110,164,0,0,20,17,30,43,30,4,70,128,0,0,30,53,0,0,0,0,0,0,220,1452,0,0,0,0,0,0,20,22,0,0,220,1005,220,1052,0,0,0,0,50,110,170,508
2,1,AL,35178,4,120,30,90,0,80,280,80,0,0,0,0,0,30,40,9905,120,10001,100,7247,40,69,20,238,20,141,40,24,0,0,0,0,0,0,40,1274,0,0,0,30,667,0,0,30,96,0,0,...,0,0,0,0,40,73,0,0,0,0,0,0,0,0,30,60,0,0,0,0,0,0,0,0,0,0,120,1149,0,0,0,0,0,0,0,0,0,0,110,889,110,931,0,0,0,0,40,62,80,274
3,1,AL,35178,5,110,0,90,0,80,280,90,0,0,0,0,0,0,60,14233,110,14454,120,12722,80,81,40,158,30,140,60,84,30,373,40,992,30,1163,50,1471,0,0,0,40,1083,0,0,50,221,0,0,...,0,0,0,0,40,58,0,0,0,0,0,0,0,0,20,33,0,0,20,60,0,0,0,0,0,0,110,1907,0,0,0,0,0,0,0,0,0,0,110,1757,110,1829,0,0,0,0,50,420,70,295
4,1,AL,35178,6,20,0,20,0,0,50,0,0,0,0,0,0,0,0,7392,20,7392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,1215,0,0,0,0,0,0,0,0,0,0,20,1464,20,1551,0,0,0,0,0,0,0,0

3. Carregue o arquivo tax_data_2016.csv, visualize o atributo dtypes do dataframe e observe os tipos de dados de CEP e agi_stub.

In [21]:

dado = pd.read_csv(path, usecols=['zipcode','agi_stub'])
dado.head(5)

display(dado.dtypes)

zipcode     int64
agi_stub    int64
dtype: object

4. Você deve ter observado que a coluna agi_stub contém números que correspondem a categorias de renda, e CEP tem valores de 5 dígitos que devem ser strings -- tratá-los como inteiros significa que perdemos 0s iniciais, que são significativos. 
Defina os tipos de dados corretos criando um dicionario chamado null_values, especificando que 0s na coluna CEP devem ser considerados valores NA.
Depois, carregue tax_data_2016.csv, usando o argumento na_values e o dicionário para garantir que CEPs inválidos sejam tratados como ausentes.

In [4]:
null_values = {'zipcode':['0000000']}
dados= pd.read_csv(path,na_values=null_values,dtype={'agi_stub':'category','zipcode':'str'})
dados

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,...,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,1,AL,0,1,815440,477700,105350,221200,440830,1296920,491310,24730,16610,8130,5440,31550,225140,150920,10610343,815440,10787121,651680,8466376,90040,57551,42420,74527,38170,51048,11830,5328,144430,765184,34770,20594,38510,240402,104980,1038534,8310,22770,65220,37560,73490,7900,17497,145820,176778,1340,308,...,0,0,18830,6579,101150,34290,1760,68,6620,2205,27490,15002,32490,5582,28940,8858,1140,471,113880,155301,54520,230494,56460,231566,18020,10199,755160,2119297,363420,1097024,333760,981026,229900,291625,61350,57108,28510,14474,254700,160665,367320,330066,0,0,0,0,63420,51444,711580,1831661
1,1,AL,0,2,495830,211930,142340,128890,272440,996240,360480,10890,7100,3780,280,11770,118460,109680,17839904,495830,18020908,427840,14690098,89460,63622,39400,94307,35060,67289,47330,26083,65350,258861,31040,50118,36020,348074,100030,1812761,8920,15170,45546,91310,605042,10340,69499,96260,181004,14260,3476,...,0,0,17200,13087,216450,191023,6320,291,30880,17180,43580,45248,77770,14984,122630,108314,12690,6759,38490,84581,24960,96905,27540,110068,21690,14515,485140,2062531,138800,291932,115640,245939,102530,144943,33880,30970,5140,4460,375320,877407,398050,984297,0,0,0,0,74090,110889,416090,1173463
2,1,AL,0,3,263390,83420,137870,36340,154880,584000,182880,2480,1270,1210,0,150,41910,75570,16193076,263390,16351320,225610,12476022,80410,64816,38990,121115,35340,89415,58720,40132,41390,259064,31240,85650,29450,388970,73030,1836648,8470,7460,24614,63740,961406,11580,126140,69510,158244,8520,2146,...,40,96,4180,7590,113150,165544,9150,684,18100,9762,22780,29166,18710,2977,75270,113174,9740,5867,27370,68645,2400,8954,5780,22602,4510,4481,259650,1769024,70,24,20,7,9560,12495,16820,15588,0,0,249560,1264586,253180,1349246,0,0,0,0,64000,143060,195130,543284
3,1,AL,0,4,167190,29420,124060,10610,99700,421720,130160,620,390,230,0,0,18560,51540,14513312,167190,14646693,144290,10900188,67750,59882,33700,124605,30700,94076,53210,42499,28910,240845,27320,103892,22930,411954,53260,1666592,5510,3850,13372,42870,874160,8780,145281,49910,133381,8580,2323,...,260,609,520,1445,74870,127722,7530,1507,15060,8574,17250,22630,0,0,53970,88853,5770,2765,19550,56524,20,84,840,3148,510,724,165540,1693476,0,0,0,0,130,197,12040,11117,0,0,165330,1352397,165830,1425430,0,0,0,0,45020,128920,117410,381329
4,1,AL,0,5,217440,20240,188080,4880,129410,601040,195990,680,660,20,0,0,11620,68080,29375736,217440,29696755,193550,21806247,116090,145219,69540,375343,64870,300101,110430,118782,43180,684832,59160,506542,34750,909488,74160,2988298,8180,2280,8380,50010,1195287,24980,828015,77820,321019,12040,3192,...,1930,4531,140,580,95820,130089,19270,3949,21690,12377,20970,29469,0,0,46670,62728,6750,2896,31130,127140,0,0,160,717,180,360,215570,4072975,0,0,0,0,0,0,18770,17844,0,0,216500,3760298,216720,3922449,390,155,60,19,82940,423629,126130,506526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,1,AL,36584,4,30,0,30,0,20,80,30,0,0,0,0,0,0,0,2572,30,2572,30,2283,20,2,0,0,0,0,20,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,30,47,0,0,0,0,0,0,0,0,20,32,0,0,0,0,0,0,0,0,0,0,30,292,0,0,0,0,0,0,0,0,0,0,30,207,30,208,0,0,0,0,0,0,40,160
2997,1,AL,36584,5,30,0,30,0,20,80,30,0,0,0,0,0,0,0,3755,30,3755,30,3060,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,510,0,0,0,0,0,0,0,0,0,0,30,442,30,465,0,0,0,0,0,0,0,0
2998,1,AL,36584,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2999,1,AL,36585,1,140,80,20,40,100,240,90,0,0,0,0,0,40,30,1834,140,1875,100,1313,40,11,0,0,0,0,0,0,20,105,20,-16,0,0,30,295,0,0,0,20,144,0,0,40,41,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,20,4,0,0,0,0,30,35,0,0,0,0,0,0,130,376,60,209,60,187,40,46,0,0,0,0,40,26,60,51,0,0,0,0,0,0,120,331
3000,1,AL,36585,2,90,40,30,40,60,180,60,0,0,0,0,0,30,20,3235,90,3235,80,2621,0,0,0,0,0,0,20,13,30,58,0,0,30,408,40,678,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,50,35,0,0,0,0,0,0,0,0,30,26,0,0,0,0,0,0,0,0,0,0,90,365,30,63,30,54,20,23,0,0,0,0,70,146,80,165,0,0,0,0,40,62,80,228

5. Leia o arquivo fcc_survey.xlsx, atribua-o à variável survey_responses e imprima os primeiros registros de survey_responses.

In [6]:

survey_responses = pd.read_excel(path1)
survey_responses.head(5)

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CodeEventCoffee,CodeEventConferences,CodeEventDjangoGirls,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWomenCode,CodeEventWorkshop,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,Gender,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,...,NetworkID,Part1EndTime,Part1StartTime,Part2EndTime,Part2StartTime,PodcastChangeLog,PodcastCodeNewbie,PodcastCodingBlocks,PodcastDeveloperTea,PodcastDotNetRocks,PodcastHanselminutes,PodcastJSJabber,PodcastJsAir,PodcastNone,PodcastOther,PodcastProgrammingThrowDown,PodcastRubyRogues,PodcastSEDaily,PodcastShopTalk,PodcastTalkPython,PodcastWebAhead,ResourceBlogs,ResourceBooks,ResourceCodeWars,ResourceCodecademy,ResourceCoursera,ResourceDevTips,ResourceEdX,ResourceEggHead,ResourceFCC,ResourceGoogle,ResourceHackerRank,ResourceKhanAcademy,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceReddit,ResourceSkillCrush,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,United States of America,United States of America,office and administrative support,NaN,Employed for wages,NaN,NaN,0.0,male,0.0,1.0,1.0,1.0,0.0,0.0,1.0,NaN,30.0,cef35615d61b202f1dc794ef2746df14,48fd66e15301df9727e13e6e80aef941,32000.0,0.0,...,2c6f0af42c,2016-03-29 21:24:53,2016-03-29 21:23:13,2016-03-29 21:27:25,2016-03-29 21:24:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,United States of America,United States of America,food and beverage,NaN,Employed for wages,NaN,50000.0,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,30.0,323e5a113644d18185c743c241407754,a8cd67193184084b1e32b362225bf280,15000.0,0.0,...,d048ac774d,2016-03-29 21:27:09,2016-03-29 21:24:59,2016-03-29 21:29:10,2016-03-29 21:27:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Front-end happy hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,United States of America,United States of America,finance,NaN,Employed for wages,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,20.0,b29a1027e5cd062e654a63764157461d,129b4479808fe006e768502b957a0c52,48000.0,0.0,...,241513bbbe,2016-03-29 21:27:11,2016-03-29 21:25:37,2016-03-29 21:28:21,2016-03-29 21:27:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,45.0,United States of America,United States of America,"arts, entertainment, sports, or media",NaN,Employed for wages,NaN,65000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,20.0,04a11e4bcb573a1261eb0d9948d32637,7313b696ac8f0517a3d0ec7725039bb2,43000.0,0.0,...,809298000000000071062979228803985833984,2016-03-29 21:28:47,2016-03-29 21:21:37,2016-03-29 21:30:51,2016-03-29 21:28:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,United States of America,United States of America,education,NaN,Employed for wages,NaN,45000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,25.0,9368291c93d5d5f5c8cdb1a575e18bec,d0f75544984896ccfd361af6d9b26047,6000.0,1.0,...,cdc466b1ee,2016-03-29 21:29:27,2016-03-29 21:26:22,2016-03-29 21:31:54,2016-03-29 21:29:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN

6. Crie uma string chamada col_string, especificando que os pandas devem carregar a coluna AD e o intervalo AW até BA.
Carregue fcc_survey.xlsx, definindo ``skiprows`` e ``usecols`` para ignorar as duas primeiras linhas e obter apenas as colunas em col_string.
Visualize os nomes das colunas selecionadas no dataframe resultante.

In [12]:
col_string ='AD:AW,AW:BA'
survey_responses=pd.read_excel(path1,skiprows=2, usecols=col_string)
display(survey_responses.head(5))

,United States of America.1,food and beverage,NA.24,Employed for wages,NA.25,50000,NA.26,male,NA.27,0.1,0.2,1,NA.28,0.3,NA.29,NA.30,30,323e5a113644d18185c743c241407754,a8cd67193184084b1e32b362225bf280,15000,0.4,0.5,0.6,1.1
0,United States of America,finance,NaN,Employed for wages,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,20.0,b29a1027e5cd062e654a63764157461d,129b4479808fe006e768502b957a0c52,48000.0,0.0,0.0,0.0,0.0
1,United States of America,"arts, entertainment, sports, or media",NaN,Employed for wages,NaN,65000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,20.0,04a11e4bcb573a1261eb0d9948d32637,7313b696ac8f0517a3d0ec7725039bb2,43000.0,0.0,0.0,0.0,1.0
2,United States of America,education,NaN,Employed for wages,NaN,45000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,25.0,9368291c93d5d5f5c8cdb1a575e18bec,d0f75544984896ccfd361af6d9b26047,6000.0,1.0,0.0,0.0,1.0
3,United States of America,finance,NaN,Self-employed freelancer,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,5.0,dd0e77eab9270e4b67c19b0d6bbf621b,66d363b06745fa484082f33044ed4598,40000.0,0.0,0.0,0.0,0.0
4,Singapore,software development,NaN,Employed for wages,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,1.0,NaN,NaN,8.0,7599c0aa0419b59fd11ffede98a3665d,1f57b280385f41a8f089713894ffe87c,32000.0,0.0,0.0,1.0,0.0

7. Crie um dataframe a partir do arquivo `fcc_survey.xlsx` passando a posição da segunda aba para ``sheet_name``.

In [13]:
survey_responses=pd.read_excel(path1,sheet_name=1)
display(survey_responses.head(5))

,Age,AttendedBootcamp,BootcampFinish,BootcampLoanYesNo,BootcampName,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventConferences,CodeEventDjangoGirls,CodeEventFCC,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWkdBootcamps,CodeEventWomenCode,CodeEventWorkshops,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,FirstDevJob,Gender,GenderOther,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,IsReceiveDisabilitiesBenefits,...,PodcastJSJabber,PodcastNone,PodcastOther,PodcastProgThrowdown,PodcastRubyRogues,PodcastSEDaily,PodcastSERadio,PodcastShopTalk,PodcastTalkPython,PodcastTheWebAhead,ResourceCodecademy,ResourceCodeWars,ResourceCoursera,ResourceCSS,ResourceEdX,ResourceEgghead,ResourceFCC,ResourceHackerRank,ResourceKA,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceSkillcrush,ResourceSO,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3S,SchoolDegree,SchoolMajor,StudentDebtOwe,YouTubeCodeCourse,YouTubeCodingTrain,YouTubeCodingTut360,YouTubeComputerphile,YouTubeDerekBanas,YouTubeDevTips,YouTubeEngineeredTruth,YouTubeFCC,YouTubeFunFunFunction,YouTubeGoogleDev,YouTubeLearnCode,YouTubeLevelUpTuts,YouTubeMIT,YouTubeMozillaHacks,YouTubeOther,YouTubeSimplilearn,YouTubeTheNewBoston
0,27.0,0.0,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15 to 29 minutes,Canada,Canada,software development and IT,NaN,Employed for wages,NaN,NaN,NaN,NaN,female,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,15.0,02d9465b21e8bd09374b0066fb2d5614,eb78c1c3ac6cd9052aec557065070fbf,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34.0,0.0,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,United States of America,NaN,NaN,Not working but looking for work,NaN,35000.0,NaN,NaN,male,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,10.0,5bfef9ecb211ec4f518cfc1d2a6f3e0c,21db37adb60cdcafadfa7dca1b13b6b1,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21.0,0.0,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15 to 29 minutes,United States of America,United States of America,software development and IT,NaN,Employed for wages,NaN,70000.0,NaN,NaN,male,NaN,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,25.0,14f1863afa9c7de488050b82eb3edd96,21ba173828fbe9e27ccebaf4d5166a55,13000.0,1.0,0.0,...,NaN,NaN,Codenewbie,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,high school diploma or equivalent (GED),NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I work from home,Brazil,Brazil,software development and IT,NaN,Employed for wages,NaN,40000.0,0.0,NaN,male,NaN,0.0,1.0,1.0,1.0,1.0,0.0,0.0,40000.0,14.0,91756eb4dc280062a541c25a3d44cfb0,3be37b558f02daae93a6da10f83f0c77,24000.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portugal,Portugal,NaN,NaN,Not working but looking for work,NaN,140000.0,NaN,NaN,female,NaN,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,10.0,aa3f061a1949a90b27bef7411ecd193f,d7c56bbf2c7b62096be9db010e86d96d,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,bachelor's degree,Information Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

8. Carregue as planilhas de 2016 e 2017 por nome em variáveis separadas. Calcule a média da coluna Age para as diferentes abas do arquivo.

In [26]:
#ler planilhas
df_2016=pd.read_excel(path1,sheet_name='2016')
df_2017=pd.read_excel(path1,sheet_name='2017')

#calcular média
media_2016 = df_2016['Age'].mean()
media_2017 = df_2017['Age'].mean()

#imprimir média
print('Média 2016: {:.4f}'.format(media_2016),'e Média 2017: {:.4f}'.format(media_2017))

Média 2016: 29.1754 e Média 2017: 27.6919

9. Concatene as diferentes abas do arquivo `fcc_survey.xlsx` em apenas um dataframe. Calcule a média da coluna Age para a concatenação das abas do arquivo.

In [27]:
#ler planilhas
df_abas = pd.read_excel(path1,sheet_name=None)

#concatenar dataframe
df_concat= pd.concat(df_abas.values())

#calcular média
media = df_concat['Age'].mean()

#imprimir
print("Média da idade: {:.2f}".format(media))

Média da idade: 28.39

10.  Utilizando uma query em SQL e o banco `sqlite-sakila.db` retorne as cidades e os países, mas apenas os países que começem com a letra **B**.

In [47]:
pip install pysqlite3

Collecting pysqlite3
  Downloading pysqlite3-0.5.0.tar.gz (40 kB)
     ---------------------------------------- 40.1/40.1 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Installing collected packages: pysqlite3
  Running setup.py install for pysqlite3: started
  Running setup.py install for pysqlite3: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  DEPRECATION: pysqlite3 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  error: subprocess-exited-with-error

  × Running setup.py install for pysqlite3 did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      c:\Users\Sergio\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pysqlite3
      copying pysqlite3\dbapi2.py -> build\lib.win-amd64-cpython-311\pysqlite3
      copying pysqlite3\__init__.py -> build\lib.win-amd64-cpython-311\pysqlite3
      running build_ext
      Builds a C extension linking against libsqlite3 library
      building 'pysqlite3._sqlite3' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pysqlite3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [78]:
import sqlite3

In [79]:
conn = sqlite3.connect(r'D:/instalar/sqllite/base/sqlite-sakila.db')
cursor = conn.cursor()

In [80]:
sql = '''
         select country.country, city.city 
         from city 
         inner join country on city.country_id = country.country_id  
         where country.country like 'B%' 
         order by country.country
      '''

resultado= cursor.execute(sql)
for linha in resultado:
    print(linha)

conn.close()

('Bahrain', 'al-Manama')
('Bangladesh', 'Dhaka')
('Bangladesh', 'Jamalpur')
('Bangladesh', 'Tangail')
('Belarus', 'Mogiljov')
('Belarus', 'Molodetno')
('Bolivia', 'El Alto')
('Bolivia', 'Sucre')
('Brazil', 'Alvorada')
('Brazil', 'Angra dos Reis')
('Brazil', 'Anpolis')
('Brazil', 'Aparecida de Goinia')
('Brazil', 'Araatuba')
('Brazil', 'Bag')
('Brazil', 'Belm')
('Brazil', 'Blumenau')
('Brazil', 'Boa Vista')
('Brazil', 'Braslia')
('Brazil', 'Goinia')
('Brazil', 'Guaruj')
('Brazil', 'guas Lindas de Gois')
('Brazil', 'Ibirit')
('Brazil', 'Juazeiro do Norte')
('Brazil', 'Juiz de Fora')
('Brazil', 'Luzinia')
('Brazil', 'Maring')
('Brazil', 'Po')
('Brazil', 'Poos de Caldas')
('Brazil', 'Rio Claro')
('Brazil', 'Santa Brbara dOeste')
('Brazil', 'Santo Andr')
('Brazil', 'So Bernardo do Campo')
('Brazil', 'So Leopoldo')
('Brazil', 'Sorocaba')
('Brazil', 'Vila Velha')
('Brazil', 'Vitria de Santo Anto')
('Brunei', 'Bandar Seri Begawan')
('Bulgaria', 'Ruse')
('Bulgaria', 'Stara Zagora')